import { generateCommitMessage, generatePullRequest } from "../src/services/commitService";
import { generateCompletion } from "../src/api/aiClient";

jest.mock("../src/api/aiClient", () => ({
  generateCompletion: jest.fn(),
}));

describe("commitService", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe("generateCommitMessage", () => {
    it("should generate a commit message for a normal diff", async () => {
      const diff = `diff --git a/file.txt b/file.txt
index 83db48f..f735c8b 100644
--- a/file.txt
+++ b/file.txt
@@ -1 +1 @@
-Hello World
+Hello Universe`;

      (generateCompletion as jest.Mock).mockResolvedValue(
        "feat(core): update greeting message"
      );

      const commitMessage = await generateCommitMessage(diff);

      expect(commitMessage).toBe("feat(core): update greeting message");
      expect(generateCompletion).toHaveBeenCalledWith(
        expect.arrayContaining([
          expect.objectContaining({
            role: "user",
            content: `Here's the git diff:\n${diff}`,
          }),
        ]),
        undefined
      );
    });

    it("should pass the model parameter when specified", async () => {
      const diff = "some diff";
      const customModel = "llama-3.3-70b-versatile";

      (generateCompletion as jest.Mock).mockResolvedValue(
        "fix(api): fix connection error"
      );

      const commitMessage = await generateCommitMessage(diff, customModel);

      expect(commitMessage).toBe("fix(api): fix connection error");
      expect(generateCompletion).toHaveBeenCalledWith(
        expect.any(Array),
        customModel
      );
    });

    it("should reject invalid AI generated messages starting with 'Here is'", async () => {
      const diff = "some diff";
      (generateCompletion as jest.Mock).mockResolvedValue(
        "Here is the commit message: feat: add something"
      );

      await expect(generateCommitMessage(diff)).rejects.toThrow(
        "Invalid commit message format generated by AI."
      );
    });

    it("should handle API failure by rethrowing", async () => {
      const diff = "some diff";
      (generateCompletion as jest.Mock).mockRejectedValue(
        new Error("Groq API error: Rate limit reached")
      );

      await expect(generateCommitMessage(diff)).rejects.toThrow(
        "Groq API error: Rate limit reached"
      );
    });
  });

  describe("generatePullRequest", () => {
    it("should generate a pull request and pass model", async () => {
      const diff = "some diff";
      const customModel = "gemini-2.0-flash";

      (generateCompletion as jest.Mock).mockResolvedValue(
        "### PR Title\nAdd new features\n\n### PR Description\nDetails..."
      );

      const pr = await generatePullRequest(diff, customModel);

      expect(pr).toContain("### PR Title");
      expect(generateCompletion).toHaveBeenCalledWith(
        expect.any(Array),
        customModel
      );
    });
  });
});

